CREATE SCHEMA IF NOT EXISTS LIBRARY_SCHEMA;

CREATE TABLE IF NOT EXISTS BOOK (
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(20) NOT NULL PRIMARY KEY,
    category VARCHAR(50),
    borrower VARCHAR(255)
);