version: '3'
services:
  library-sql-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: library-sql-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
